In [32]:
import numpy as np
import pandas as pd

In [33]:
batsman = pd.read_excel('6671501a18c55_round2_input.xlsx', sheet_name='batsman_scorecard')

In [34]:
batsman.head()

,match id,batsman,batsman_id,batsman_dob,batsman_details,is_batsman_captain,is_batsman_keeper,inning,runs,balls_faced,...,bowler_id,bowler_dob,bowler_details,is_bowler_keeper,is_bowler_captain,strike_rate,Fours,Sixes,match_dt,ingestion_timestamp
0,8587795,AJ Fh,37351,1986-11-17,AUS:Right-hand bat:Slow left-arm orthodox:,1,0,2,14,15,...,6718844.0,1997-02-05,AUS:Right-hand bat:Right-arm fast:,0.0,0.0,93.33,1.0,NaN,2021-01-08,2022-03-22 12:43:21
1,8587795,Md Ni,181404,1985-01-01,AFG:Right-hand bat:Right-arm offbreak:,0,0,2,71,41,...,NaN,NaN,NaN,NaN,NaN,173.17,9.0,2.0,2021-01-08,2022-03-22 12:43:21
2,8587795,JW Ws,1635773,1988-08-13,AUS:Right-hand bat:Right-arm medium:,0,0,1,16,13,...,NaN,NaN,NaN,NaN,NaN,123.08,1.0,NaN,2021-01-08,2022-03-22 12:43:21
3,8587795,DR Bs,2170762,1991-04-30,ENG:Right-hand bat:Slow left-arm orthodox:,0,0,1,2,4,...,1905847.0,1991-02-12,AUS:Right-hand bat:Right-arm fast-medium:,0.0,0.0,50.00,NaN,NaN,2021-01-08,2022-03-22 12:43:21
4,8587795,AT Cy,2285051,1991-08-27,AUS:Left-hand bat:None:,1,1,1,42,25,...,1594319.0,1988-12-18,PAK:Left-hand bat:Slow left-arm orthodox:,0.0,0.0,168.00,3.0,3.0,2021-01-08,2022-03-22 12:43:21

In [35]:
batsman.isnull().sum()

match id                   0
batsman                    0
batsman_id                 0
batsman_dob                0
batsman_details            0
is_batsman_captain         0
is_batsman_keeper          0
inning                     0
runs                       0
balls_faced                0
over_faced_first           0
wicket kind             5461
out_by_bowler           5461
out_by_fielder             6
bowler_id               6507
bowler_dob              6507
bowler_details          6507
is_bowler_keeper        5922
is_bowler_captain       6507
strike_rate                0
Fours                  10464
Sixes                  15684
match_dt                   0
ingestion_timestamp        0
dtype: int64

In [36]:
# List of columns to keep
columns_to_keep = [
    'batsman',                   
    'batsman_id',
    'batsman_details',                
    'is_batsman_keeper',         
    'runs',                      
    'balls_faced',  
    'wicket kind',                    
    'strike_rate',  
    'match_dt'             
]

# Keep only the specified columns and discard the rest
batsman = batsman[columns_to_keep]

In [37]:
batsman.head()

,batsman,batsman_id,batsman_details,is_batsman_keeper,runs,balls_faced,wicket kind,strike_rate,match_dt
0,AJ Fh,37351,AUS:Right-hand bat:Slow left-arm orthodox:,0,14,15,lbw,93.33,2021-01-08
1,Md Ni,181404,AFG:Right-hand bat:Right-arm offbreak:,0,71,41,NaN,173.17,2021-01-08
2,JW Ws,1635773,AUS:Right-hand bat:Right-arm medium:,0,16,13,NaN,123.08,2021-01-08
3,DR Bs,2170762,ENG:Right-hand bat:Slow left-arm orthodox:,0,2,4,caught,50.00,2021-01-08
4,AT Cy,2285051,AUS:Left-hand bat:None:,1,42,25,caught,168.00,2021-01-08

In [38]:
batsman = batsman.sort_values('batsman_id')

In [39]:
final_output = 'batsman.xlsx'
batsman.to_excel(final_output, index=False)

In [40]:
# Replace NaN values with empty strings and ensure all entries are strings
batsman['wicket kind'] = batsman['wicket kind'].fillna('').astype(str)

# Creating 'Out/Not Out' column
batsman['Out_Not_Out'] = batsman['wicket kind'].apply(lambda x: 0 if len(x) == 0 else 1)

In [41]:
batsman.head()

,batsman,batsman_id,batsman_details,is_batsman_keeper,runs,balls_faced,wicket kind,strike_rate,match_dt,Out_Not_Out
738,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,8,11,caught,72.73,2021-01-01,1
749,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,2,4,caught,50.00,2021-01-02,1
775,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,0,3,caught,0.00,2021-01-04,1
16918,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,4,caught,25.00,2022-12-17,1
8289,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,39,15,caught,260.00,2021-08-07,1

In [42]:
batsman = batsman.drop('wicket kind', axis=1)

In [43]:
batsman.head()

,batsman,batsman_id,batsman_details,is_batsman_keeper,runs,balls_faced,strike_rate,match_dt,Out_Not_Out
738,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,8,11,72.73,2021-01-01,1
749,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,2,4,50.00,2021-01-02,1
775,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,0,3,0.00,2021-01-04,1
16918,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,4,25.00,2022-12-17,1
8289,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,39,15,260.00,2021-08-07,1

In [44]:
def calculate_batsman_stats(group):
    total_runs = group['runs'].sum()
    total_balls = group['balls_faced'].sum()
    times_out = group['Out_Not_Out'].sum()
    hundreds = (group['runs'] >= 100).sum()
    fifties = (group['runs'] >= 50).sum()
    return pd.Series({
        'Total Runs': total_runs,
        'Total Balls Faced': total_balls,
        'Total Number of Times Out': times_out,
        "100's": hundreds,
        "50's": fifties
    })

In [45]:
# Group by 'batsman_id' and apply the calculation function
batsman_stats = batsman.groupby('batsman_id').apply(calculate_batsman_stats).reset_index()

# Merge the calculated stats back into the original DataFrame
batsman = batsman.merge(batsman_stats, on='batsman_id', how='left')

In [46]:
final_output = 'batsman2.0.xlsx'
batsman.to_excel(final_output, index=False)

In [47]:
batsman['Strike Rate'] = (batsman['Total Runs'] / batsman['Total Balls Faced']) * 100
batsman['Avg'] = (batsman['Total Runs'] / batsman['Total Number of Times Out'])

In [48]:
batsman = batsman.rename(columns={"100's":"100s","50's":"50s"})

In [49]:
batsman.head()

,batsman,batsman_id,batsman_details,is_batsman_keeper,runs,balls_faced,strike_rate,match_dt,Out_Not_Out,Total Runs,Total Balls Faced,Total Number of Times Out,100s,50s,Strike Rate,Avg
0,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,8,11,72.73,2021-01-01,1,10,18,3,0,0,55.555556,3.333333
1,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,2,4,50.00,2021-01-02,1,10,18,3,0,0,55.555556,3.333333
2,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,0,3,0.00,2021-01-04,1,10,18,3,0,0,55.555556,3.333333
3,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,4,25.00,2022-12-17,1,729,509,34,0,2,143.222004,21.441176
4,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,39,15,260.00,2021-08-07,1,729,509,34,0,2,143.222004,21.441176

In [50]:
batsman.shape

(24875, 16)

In [51]:
batsman.columns

Index(['batsman', 'batsman_id', 'batsman_details', 'is_batsman_keeper', 'runs',
       'balls_faced', 'strike_rate', 'match_dt', 'Out_Not_Out', 'Total Runs',
       'Total Balls Faced', 'Total Number of Times Out', '100s', '50s',
       'Strike Rate', 'Avg'],
      dtype='object')

In [52]:
def strike_rate_weight(sr):
    if sr >= 150:
        return 50
    elif sr >= 100:
        return 40
    elif sr >= 80:
        return 30
    else:
        return 0

def avg_weight(avg):
    if avg >= 50:
        return 30
    elif avg >= 40:
        return 20
    elif avg >= 30:
        return 10
    else:
        return 5

def hundreds_weight(hundreds):
    if hundreds >= 3:
        return 30
    elif hundreds == 2:
        return 20
    elif hundreds == 1:
        return 10
    else:
        return 0

def fifties_weight(fifties):
    if fifties >= 5:
        return 20
    elif fifties >= 3:
        return 10
    elif fifties >= 1:
        return 5
    else:
        return 0

# Apply the functions to the respective columns
batsman['Strike Rate'] = batsman['Strike Rate'].apply(strike_rate_weight)
batsman['Avg'] = batsman['Avg'].apply(avg_weight)
batsman['100s'] = batsman['100s'].apply(hundreds_weight)
batsman['50s'] = batsman['50s'].apply(fifties_weight)

In [53]:
batsman.head()

,batsman,batsman_id,batsman_details,is_batsman_keeper,runs,balls_faced,strike_rate,match_dt,Out_Not_Out,Total Runs,Total Balls Faced,Total Number of Times Out,100s,50s,Strike Rate,Avg
0,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,8,11,72.73,2021-01-01,1,10,18,3,0,0,0,5
1,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,2,4,50.00,2021-01-02,1,10,18,3,0,0,0,5
2,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,0,3,0.00,2021-01-04,1,10,18,3,0,0,0,5
3,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,4,25.00,2022-12-17,1,729,509,34,0,5,40,5
4,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,39,15,260.00,2021-08-07,1,729,509,34,0,5,40,5

In [54]:
batsman['cumulative_points'] = batsman['Strike Rate'] + batsman['Avg'] + batsman['100s'] + batsman['50s']

In [55]:
batsman.head()

,batsman,batsman_id,batsman_details,is_batsman_keeper,runs,balls_faced,strike_rate,match_dt,Out_Not_Out,Total Runs,Total Balls Faced,Total Number of Times Out,100s,50s,Strike Rate,Avg,cumulative_points
0,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,8,11,72.73,2021-01-01,1,10,18,3,0,0,0,5,5
1,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,2,4,50.00,2021-01-02,1,10,18,3,0,0,0,5,5
2,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,0,3,0.00,2021-01-04,1,10,18,3,0,0,0,5,5
3,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,4,25.00,2022-12-17,1,729,509,34,0,5,40,5,50
4,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,39,15,260.00,2021-08-07,1,729,509,34,0,5,40,5,50

In [56]:
# Step 1: Calculate Consistency Score based on strike rate
batsman['std_strike_rate'] = batsman.groupby('batsman_id')['strike_rate'].transform('std')

# Step 2: Calculate Recency Score using Exponentially Weighted Average for strike rate
batsman = batsman.sort_values(by=['batsman_id', 'match_dt'])
batsman['exp_weighted_avg_sr'] = batsman.groupby('batsman_id')['strike_rate'].transform(lambda x: x.ewm(span=5, adjust=False).mean())

# Normalize consistency and recency scores
batsman['std_strike_rate_norm'] = (batsman['std_strike_rate'] - batsman['std_strike_rate'].min()) / (batsman['std_strike_rate'].max() - batsman['std_strike_rate'].min())
batsman['exp_weighted_avg_sr_norm'] = (batsman['exp_weighted_avg_sr'] - batsman['exp_weighted_avg_sr'].min()) / (batsman['exp_weighted_avg_sr'].max() - batsman['exp_weighted_avg_sr'].min())

# Combine Scores
# Assuming we give equal weight to each component
batsman['final_score'] = (batsman['cumulative_points'] / batsman['cumulative_points'].max()) * 0.7 + \
                         (1 - batsman['std_strike_rate_norm']) * 0.2 + \
                         batsman['exp_weighted_avg_sr_norm'] * 0.1

# Get the final score for each batsman
final_batsman_scores = batsman.groupby('batsman_id')['final_score'].mean().reset_index()

print(final_batsman_scores)

      batsman_id  final_score
0          31464     0.214412
1          34061     0.473575
2          36665     0.463971
3          37351     0.592053
4          41740     0.625778
...          ...          ...
2058     9822322          NaN
2059     9822392          NaN
2060     9874052          NaN
2061     9883250          NaN
2062     9899140          NaN

[2063 rows x 2 columns]

In [64]:
batsman.head()

,batsman,batsman_id,batsman_details,is_batsman_keeper,runs,balls_faced,strike_rate,match_dt,Out_Not_Out,Total Runs,...,100s,50s,Strike Rate,Avg,cumulative_points,std_strike_rate,exp_weighted_avg_sr,Consistency_Score,Recency_Score,final_score
6396,Md Rn,2263736,PAK:Right-hand bat:None:,1,104,64,162.50,2021-02-11,0,4031,...,20,20,40,30,110,43.395586,162.50,0.160249,0.270833,0.895034
3763,AD Hs,1749075,ENG:Right-hand bat:Right-arm medium:,0,45,19,236.84,2021-01-01,1,3203,...,30,20,50,10,110,73.266110,236.84,0.270553,0.394733,0.885363
15552,JP Is,4635658,AUS:Right-hand bat:None:,1,72,41,175.61,2021-01-03,0,1796,...,30,20,50,10,110,59.485986,175.61,0.219667,0.292683,0.885335
6644,GJ Ml,2275195,AUS:Right-hand bat:Right-arm offbreak:,0,70,37,189.19,2021-01-02,1,2480,...,30,20,50,10,110,75.142067,189.19,0.277480,0.315317,0.876036
5982,JC Br,2162782,ENG:Right-hand bat:None:,1,28,24,116.67,2021-03-12,1,3498,...,30,20,40,20,110,58.786308,116.67,0.217083,0.194450,0.876028

In [63]:
batsman.rename(columns={'std_strike_rate_norm': 'Consistency_Score', 'exp_weighted_avg_sr_norm': 'Recency_Score'}, inplace=True)

In [65]:
batsman = batsman.drop_duplicates(subset=['batsman_id'], keep='first')

In [ ]:
batsman['Total Points']=batsman['final_score']*100

In [59]:
batsman=batsman.sort_values(by="Total Points",ascending=False)

In [60]:
batsman.head()

,batsman,batsman_id,batsman_details,is_batsman_keeper,runs,balls_faced,strike_rate,match_dt,Out_Not_Out,Total Runs,...,100s,50s,Strike Rate,Avg,cumulative_points,std_strike_rate,exp_weighted_avg_sr,std_strike_rate_norm,exp_weighted_avg_sr_norm,final_score
6396,Md Rn,2263736,PAK:Right-hand bat:None:,1,104,64,162.50,2021-02-11,0,4031,...,20,20,40,30,110,43.395586,162.50,0.160249,0.270833,0.895034
3763,AD Hs,1749075,ENG:Right-hand bat:Right-arm medium:,0,45,19,236.84,2021-01-01,1,3203,...,30,20,50,10,110,73.266110,236.84,0.270553,0.394733,0.885363
15552,JP Is,4635658,AUS:Right-hand bat:None:,1,72,41,175.61,2021-01-03,0,1796,...,30,20,50,10,110,59.485986,175.61,0.219667,0.292683,0.885335
6644,GJ Ml,2275195,AUS:Right-hand bat:Right-arm offbreak:,0,70,37,189.19,2021-01-02,1,2480,...,30,20,50,10,110,75.142067,189.19,0.277480,0.315317,0.876036
5982,JC Br,2162782,ENG:Right-hand bat:None:,1,28,24,116.67,2021-03-12,1,3498,...,30,20,40,20,110,58.786308,116.67,0.217083,0.194450,0.876028

In [61]:
final_output = 'batsman_ranking.xlsx'
batsman.to_excel(final_output, index=False)

In [62]:
v

NameError: name 'v' is not defined

In [ ]:
import numpy as np
import pandas as pd

def calculate_consistency(group):
    runs = group['runs']
    total_runs = group['Total Runs'].iloc[0]
    times_out = group['Total Number of Times Out'].iloc[0]
    
    # Calculate average per innings
    avg_per_innings = total_runs / len(runs)
    
    # Calculate average per dismissal (this is what's stored in 'Avg')
    avg_per_dismissal = total_runs / times_out if times_out > 0 else total_runs
    
    # Calculate standard deviation of runs
    std_dev = np.std(runs)
    
    # Calculate Coefficient of Variation (CV) using avg_per_innings
    cv = std_dev / avg_per_innings if avg_per_innings > 0 else 0
    
    # Convert CV to a consistency score
    consistency_score = 1 - cv
    
    # Normalize to ensure the score is between 0 and 1
    return pd.Series({'consistency_score': max(0, min(1, consistency_score))})

# Apply the consistency function to each group (each batsman)
batsman['consistency_score'] = batsman.groupby('batsman_id').apply(calculate_consistency).reset_index(level=0, drop=True)

def calculate_recency(group):
    runs = group['runs']
    dates = pd.to_datetime(group['match_dt'])
    half_life = 30  # Number of days after which the weight becomes half
    
    # Calculate time difference from the most recent match for this batsman
    time_diff = (dates.max() - dates).dt.days
    
    # Calculate weights based on time difference
    weights = 0.5 ** (time_diff / half_life)
    
    # Calculate weighted average of runs
    recency_score = np.average(runs, weights=weights)
    
    return recency_score

# Apply the recency function to each group (each batsman)
batsman['recency_score'] = batsman.groupby('batsman_id').apply(calculate_recency)

# Normalize recency score globally after calculating for each batsman
batsman['recency_score'] = (batsman['recency_score'] - batsman['recency_score'].min()) / (batsman['recency_score'].max() - batsman['recency_score'].min())

def calculate_combined_score(row, weights=(0.3, 0.3, 0.4)):
    return weights[0] * row['consistency_score'] + weights[1] * row['recency_score'] + weights[2] * row['cumulative_points']

batsman['combined_score'] = batsman.apply(calculate_combined_score, axis=1)

# Sort batsmen by combined score
ranked_batsmen = batsman.sort_values('combined_score', ascending=False)

# Remove duplicates, keeping the first occurrence of each batsman_id
unique_batsmen = ranked_batsmen.drop_duplicates(subset='batsman_id', keep='first')

# Reset the index if needed
unique_batsmen = unique_batsmen.reset_index(drop=True)

In [ ]:
final_output = 'batsman_weighted.xlsx'
unique_batsmen.to_excel(final_output, index=False)

In [ ]:
def calculate_consistency(batsman, batsman_id):
    # Filter data for the specific batsman
    batsman_data = batsman[batsman['batsman_id'] == batsman_id]
    
    # Calculate the standard deviation of runs
    std_dev = batsman_data['runs'].std()
    
    return std_dev

# Create a new column for consistency
batsman['consistency'] = None

# Calculate and assign consistency for each unique batsman_id
for id in batsman['batsman_id'].unique():
    consistency_value = calculate_consistency(batsman, id)
    batsman.loc[batsman['batsman_id'] == id, 'consistency'] = consistency_value

In [ ]:
batsman.head(20)

,batsman,batsman_id,batsman_details,is_batsman_keeper,runs,balls_faced,strike_rate,match_dt,Out_Not_Out,Total Runs,Total Balls Faced,Total Number of Times Out,100s,50s,Strike Rate,Avg,cumulative_points,consistency
0,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,8,11,72.73,2021-01-01,1,10,18,3,0,0,0,5,5,4.163332
1,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,2,4,50.00,2021-01-02,1,10,18,3,0,0,0,5,5,4.163332
2,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,0,3,0.00,2021-01-04,1,10,18,3,0,0,0,5,5,4.163332
3,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,4,25.00,2022-12-17,1,729,509,34,0,5,40,5,50,15.309219
4,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,39,15,260.00,2021-08-07,1,729,509,34,0,5,40,5,50,15.309219
5,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,4,1,400.00,2023-01-06,0,729,509,34,0,5,40,5,50,15.309219
6,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,49,23,213.04,2021-01-26,0,729,509,34,0,5,40,5,50,15.309219
7,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,3,3,100.00,2021-08-09,1,729,509,34,0,5,40,5,50,15.309219
8,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,3,33.33,2021-09-26,0,729,509,34,0,5,40,5,50,15.309219
9,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,11,7,157.14,2023-01-01,1,729,509,34,0,5,40,5,50,15.309219
10,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,4,25.00,2021-10-06,1,729,509,34,0,5,40,5,50,15.309219
11,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,4,25.00,2023-01-28,1,729,509,34,0,5,40,5,50,15.309219
12,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,0,1,0.00,2021-10-03,1,729,509,34,0,5,40,5,50,15.309219
13,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,6,5,120.00,2021-01-02,1,729,509,34,0,5,40,5,50,15.309219
14,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,0,2,0.00,2022-12-22,1,729,509,34,0,5,40,5,50,15.309219
15,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,61,38,160.53,2021-01-10,0,729,509,34,0,5,40,5,50,15.309219
16,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,3,33.33,2021-04-25,0,729,509,34,0,5,40,5,50,15.309219
17,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,7,10,70.00,2021-08-06,0,729,509,34,0,5,40,5,50,15.309219
18,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,21,15,140.00,2022-12-30,0,729,509,34,0,5,40,5,50,15.309219
19,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,12,7,171.43,2022-06-23,1,729,509,34,0,5,40,5,50,15.309219

In [ ]:
batsman = batsman.sort_values(by=['batsman_id', 'match_dt'])

In [ ]:
batsman.head(20)

,batsman,batsman_id,batsman_details,is_batsman_keeper,runs,balls_faced,strike_rate,match_dt,Out_Not_Out,Total Runs,Total Balls Faced,Total Number of Times Out,100s,50s,Strike Rate,Avg,cumulative_points,consistency
0,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,8,11,72.73,2021-01-01,1,10,18,3,0,0,0,5,5,4.163332
1,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,2,4,50.00,2021-01-02,1,10,18,3,0,0,0,5,5,4.163332
2,DG Be,31464,NZ:Right-hand bat:Right-arm medium:,0,0,3,0.00,2021-01-04,1,10,18,3,0,0,0,5,5,4.163332
13,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,6,5,120.00,2021-01-02,1,729,509,34,0,5,40,5,50,15.309219
54,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,0,2,0.00,2021-01-06,1,729,509,34,0,5,40,5,50,15.309219
15,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,61,38,160.53,2021-01-10,0,729,509,34,0,5,40,5,50,15.309219
44,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,15,5,300.00,2021-01-13,0,729,509,34,0,5,40,5,50,15.309219
42,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,7,4,175.00,2021-01-16,0,729,509,34,0,5,40,5,50,15.309219
48,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,21,16,131.25,2021-01-22,0,729,509,34,0,5,40,5,50,15.309219
47,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,0,1,0.00,2021-01-24,1,729,509,34,0,5,40,5,50,15.309219
6,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,49,23,213.04,2021-01-26,0,729,509,34,0,5,40,5,50,15.309219
49,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,20,14,142.86,2021-02-06,1,729,509,34,0,5,40,5,50,15.309219
52,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,12,5,240.00,2021-02-24,0,729,509,34,0,5,40,5,50,15.309219
50,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,27,14,192.86,2021-02-28,1,729,509,34,0,5,40,5,50,15.309219
51,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,16,9,177.78,2021-03-03,0,729,509,34,0,5,40,5,50,15.309219
53,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,3,33.33,2021-04-09,1,729,509,34,0,5,40,5,50,15.309219
39,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,2,50.00,2021-04-14,1,729,509,34,0,5,40,5,50,15.309219
16,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,1,3,33.33,2021-04-25,0,729,509,34,0,5,40,5,50,15.309219
35,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,10,12,83.33,2021-07-09,1,729,509,34,0,5,40,5,50,15.309219
33,DT Cn,34061,AUS:Right-hand bat:Right-arm fast-medium:,0,9,10,90.00,2021-07-10,1,729,509,34,0,5,40,5,50,15.309219

In [ ]:
batsman.columns

Index(['batsman', 'batsman_id', 'batsman_details', 'is_batsman_keeper', 'runs',
       'balls_faced', 'strike_rate', 'match_dt', 'Out_Not_Out', 'Total Runs',
       'Total Balls Faced', 'Total Number of Times Out', '100s', '50s',
       'Strike Rate', 'Avg', 'cumulative_points', 'consistency'],
      dtype='object')

In [ ]:
batsman.sort_values(by='cumulative_points', ascending=False, inplace=True)

In [ ]:
batsman.head()

,batsman,batsman_id,is_batsman_keeper,Strike Rate,Avg,100s,50s,cumulative_points
1514,F du Ps,313809,0,40,10,30,20,100
10157,SA Yv,3125562,0,40,10,30,20,100
6391,Md Rn,2263736,1,40,20,20,20,100
5905,JC Br,2162782,0,40,10,30,20,100
21119,Sn Gl,7491224,0,40,10,30,20,100

In [ ]:
final_output = 'batsman_weighted.xlsx'
batsman.to_excel(final_output, index=False)